### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vejbuch** [alex7kom/node-steam-web-api-key#2]
Do you help me? Thanks

```
root@vm16012:~# node /root/node_modules/steam-tradeoffers/examples/sell3.js
GHTBN
socket timed out
socket closed
connecting to 72.165.61.185:27017
connected
encrypt request
handshake complete
Logged in!
/root/node_modules/steam-web-api-key/index.js:10
  options.webCookie.forEach(function (name) {
                   ^
TypeError: Cannot read property 'forEach' of undefined
    at getAPIKey (/root/node_modules/steam-web-api-key/index.js:10:20)
    at /root/node_modules/steam-tradeoffers/examples/sell3.js:109:10
    at IncomingMessage.<anonymous> (/root/node_modules/steam/lib/handlers/user.j
s:104:9)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by vejbuch** [comment]
Please close
